server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider # 微服务提供者
  cloud:
    nacos:
      discovery:
        server-addr: 10.7.14.23:1111 # 换成Nginx的1111端口，访问集群
      # server-addr: localhost:8848 # 注册到8848服务注册与发现中心
management:
  endpoints:
    web:
      exposure:
        include: '*'
